/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.login2;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


/**
 *
 * @author radoj
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
       

Loginbutton.setContentAreaFilled(false);
SignUpbutton.setContentAreaFilled(false);
        try {
             Image img=ImageIO.read(new File("bcg.png"));
            img=img.getScaledInstance(ImageLabel.getWidth(), ImageLabel.getHeight(), 1);
                    ImageLabel.setIcon(new ImageIcon(img));
                    
                      Image img1=ImageIO.read(new File("close.png"));
            img1=img1.getScaledInstance(Exit.getWidth(), Exit.getHeight(), 1);
                    Exit.setIcon(new ImageIcon(img1));
                    
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NameLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        PasswordSeparator = new javax.swing.JPanel();
        NameSepartor = new javax.swing.JPanel();
        PasswordLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Loginbutton = new javax.swing.JButton();
        SignUpbutton = new javax.swing.JButton();
        Exit = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NameLabel.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        NameLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameLabel.setText("Name");
        NameLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameLabelFocusGained(evt);
            }
        });
        jPanel1.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        jTextField1.setBackground(new java.awt.Color(32, 33, 35));
        jTextField1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("jTextField1");
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 220, 30));

        PasswordSeparator.setBackground(new java.awt.Color(255, 255, 255));
        PasswordSeparator.setBorder(null);
        PasswordSeparator.setPreferredSize(new java.awt.Dimension(220, 20));

        javax.swing.GroupLayout PasswordSeparatorLayout = new javax.swing.GroupLayout(PasswordSeparator);
        PasswordSeparator.setLayout(PasswordSeparatorLayout);
        PasswordSeparatorLayout.setHorizontalGroup(
            PasswordSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        PasswordSeparatorLayout.setVerticalGroup(
            PasswordSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jPanel1.add(PasswordSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 2));

        NameSepartor.setBackground(new java.awt.Color(255, 255, 255));
        NameSepartor.setBorder(null);
        NameSepartor.setPreferredSize(new java.awt.Dimension(220, 20));

        javax.swing.GroupLayout NameSepartorLayout = new javax.swing.GroupLayout(NameSepartor);
        NameSepartor.setLayout(NameSepartorLayout);
        NameSepartorLayout.setHorizontalGroup(
            NameSepartorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        NameSepartorLayout.setVerticalGroup(
            NameSepartorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(NameSepartor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 220, 2));

        PasswordLabel.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Password");
        jPanel1.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(32, 33, 35));
        jPasswordField1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 220, 30));

        Loginbutton.setBackground(new java.awt.Color(32, 33, 35));
        Loginbutton.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        Loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        Loginbutton.setText("LOGIN");
        Loginbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(157, 23, 217), 1, true));
        Loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 220, 40));

        SignUpbutton.setBackground(new java.awt.Color(32, 33, 35));
        SignUpbutton.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        SignUpbutton.setForeground(new java.awt.Color(255, 255, 255));
        SignUpbutton.setText("SIGN UP");
        SignUpbutton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(157, 23, 217), 1, true));
        SignUpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(SignUpbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 220, 40));

        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExitMousePressed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 25, 25));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 420, 450));

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME TO LITEOM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 440, 80));

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PLEASE LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 440, 93));
        getContentPane().add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
       NameLabel.setForeground(new Color(157,23,217));
       NameSepartor.setBackground(new Color(157,23,217));
    }//GEN-LAST:event_jTextField1FocusGained

    private void NameLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameLabelFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_NameLabelFocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
    NameLabel.setForeground(Color.WHITE);
       NameSepartor.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
          PasswordLabel.setForeground(new Color(157,23,217));
       PasswordSeparator.setBackground(new Color(157,23,217));
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
           PasswordLabel.setForeground(Color.WHITE);
       PasswordSeparator.setBackground(Color.WHITE);
        
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void LoginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginbuttonActionPerformed
        System.err.println("SignUp");
    }//GEN-LAST:event_LoginbuttonActionPerformed

    private void SignUpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUpbuttonActionPerformed

    private void ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMousePressed
        System.err.println("Exit");
    }//GEN-LAST:event_ExitMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JButton Loginbutton;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel NameSepartor;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPanel PasswordSeparator;
    private javax.swing.JButton SignUpbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
